const REGISTATION_SUCCESS = "EN_1001";
const REGISTATION_FAIL = "EN_10002";
const LOGIN_SUCCESS = "EN_1003";
const LOGIN_FAIL = "EN_1004";
const OTP_SUCCESS = "EN_1005";
const OTP_FAIL = "EN_1006";
const INVALID_MOBILE = "EN_1007";
const INVALID_OTP = "EN_1008";
const AUTH_FAIL = "EN_1009";
const SOMETHING_WENT_WRONG = "EN_1010";
const NO_DATA_MSG = "EN_1011";
const INVALID_DATA = "EN_1012";
const OTP_RESEND_INTERVAL = "EN_1013";
const OTP_MAX_LIMIT = "EN_1014";
const IMAGE_UPLOADED = "EN_1015";
const INVALID_INPUT = "EN_1016";
const OTP_EXPIRED = "EN_1017";
const SUCCESS = "EN_1018";
const FAILED = "EN_1019";
const OOPS = "EN_1020";
const TEAM_REPORTED = "EN_1021";
const TEAM_EXITED = "EN_1022";
const TEAM_DELETED = "EN_1023";
const GAME_CREATED = "EN_1024";
const GAME_UPDATED = "EN_1025";
const GAME_DELETED = "EN_1026";
const MOBILE_EXISTED = "EN_1027";
const USER_DELETE_ERROR = "EN_1028";
const USER_DELETE = "EN_1029";
const TEAM_CREATE_FAIL = "EN_1030";
const TEAM_UPDATE_FAIL = "EN_1031";
const TEAM_MEMBER_FAIL = "EN_1032";
const TEAM_MIN_MEMBER_FAIL = "EN_1033";
const TEAM_MEMBER_REMOVE_FAIL = "EN_1034";
const TEAM_EXIT_FAIL = "EN_1035";
const TEAM_ADMIN_FAIL = "EN_1036";
const TEAM_DELETE_FAIL = "EN_1037";
const LARGE_FILE_ERROR = "EN_1038";
const LOGOUT_SUCCESS = "EN_1039";
const LOGOUT_FAILED = "EN_1040";
const USER_DELETE_ERROR_GAME = "EN_1041";
const USER_DELETE_ERROR_TEAM = "EN_1042";
const TEAM_DELETE_ERROR = "EN_1043";
const NO_GAME_FOUND = "EN_1044";
const CHECKSUM_FAIL = "EN_1045";
const NO_TEAM_FOUND = "EN_1046";

module.exports = {
  REGISTATION_SUCCESS,
  REGISTATION_FAIL,
  LOGIN_SUCCESS,
  LOGIN_FAIL,
  OTP_SUCCESS,
  OTP_FAIL,
  INVALID_MOBILE,
  INVALID_OTP,
  AUTH_FAIL,
  SOMETHING_WENT_WRONG,
  NO_DATA_MSG,
  INVALID_DATA,
  OTP_RESEND_INTERVAL,
  OTP_MAX_LIMIT,
  IMAGE_UPLOADED,
  INVALID_INPUT,
  OTP_EXPIRED,
  SUCCESS,
  FAILED,
  OOPS,
  TEAM_REPORTED,
  TEAM_EXITED,
  TEAM_DELETED,
  GAME_CREATED,
  GAME_UPDATED,
  GAME_DELETED,
  MOBILE_EXISTED,
  USER_DELETE_ERROR,
  USER_DELETE,
  TEAM_CREATE_FAIL,
  TEAM_UPDATE_FAIL,
  TEAM_MEMBER_FAIL,
  TEAM_MIN_MEMBER_FAIL,
  TEAM_MEMBER_REMOVE_FAIL,
  TEAM_EXIT_FAIL,
  TEAM_ADMIN_FAIL,
  TEAM_DELETE_FAIL,
  LARGE_FILE_ERROR,
  LOGOUT_SUCCESS,
  LOGOUT_FAILED,
  USER_DELETE_ERROR_GAME,
  USER_DELETE_ERROR_TEAM,
  TEAM_DELETE_ERROR,
  NO_GAME_FOUND,
  CHECKSUM_FAIL,
  NO_TEAM_FOUND
};
